version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@1.2.6
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: ruby:3.0.2-buster
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Gem Cache
          keys: 
            - m1-{{ checksum "Gemfile.lock" }}
            - m1- 
      - run:
          name: install bundle
          command: gem install bundler:2.2.22
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - save_cache:
          name: Save Gemfile Cache
          key: m1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.cache/gem

  deploy:
    docker:
      - image: ruby:3.0.2-buster
    executor: ruby/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - run:
          name: migrate db
          command: heroku run rake db:migrate --app circleciruby

workflows:
  ruby-app:
    jobs:
      - build
      - cypress/run
      - deploy:
          requires:
            - build
            - cypress/run
          filters:
            branches:
              only: master