version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1
  bundle-install: toshimaru/bundle-install@0.3.1

parameters:
  run_by_api:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: circledan/rubybundler:latest
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Gem Cache
          keys: 
            - m2-{{ checksum "Gemfile.lock" }}
            - m2- 
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps:
          with-cache: true
          key: gems-v2
      - save_cache:
          name: Save Gemfile Cache
          key: m2-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.cache/gem

  unit-test:
    docker:
      - image: circledan/rubybundler:latest
      - image: cimg/postgres:14.1

    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Gem Cache
          keys: 
            - m2-{{ checksum "Gemfile.lock" }}
            - m2- 
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set up DB
          command: rails db:create
      - run:
          name: Run webpack install
          command: rm bin/webpack*; rm config/webpacker.yml; rails webpacker:install
      - run:
          command: >
            mkdir -p unit-test

            bundle exec rspec spec/views --profile 10 --format RspecJunitFormatter 
            --out unit-test/results.xml --format progress
          name: Rspec views
      - store_test_results:
          path: unit-test/
      - store_artifacts:
          destination: unit-results
          path: unit-test/
      - run:
          name: run rubocop
          command: rubocop . --out check-results.xml || true
      - store_artifacts:
          path: coverage/
      - store_artifacts:
          path: check-results.xml
      - save_cache:
          name: Save Gemfile Cache
          key: m2-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.cache/gem

  lint:
    docker:
      - image: circledan/rubybundler:latest

    executor: ruby/default
    steps:
      - checkout
      #- run:
          #name: bundle install
          #command: bundle install
      - bundle-install/bundle-install:
          cache_key_prefix: bundle-v1
      - run:
          name: run rubocop
          command: rubocop . --out check-results.xml || true
      - store_artifacts:
          path: check-results.xml

  browser-test:
    docker:
      - image: circledan/rubybundler:latest
      - image: cimg/postgres:14.1

    executor: ruby/default
    steps:
      - run:
          name: rm package-lock
          command: rm -rf package-lock.json
      - checkout
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set up DB
          command: rails db:create
      - run:
          name: Run webpack install
          command: rm bin/webpack*; rm config/webpacker.yml; rails webpacker:install
      - run:
          command: >
            mkdir -p web-test

            bundle exec rspec spec/features --profile 10 --format RspecJunitFormatter 
            --out web-test/results.xml --format progress
          name: Rspec features
      - store_test_results:
          path: web-test/
      - store_artifacts:
          destination: web-results
          path: web-test/

  deploy:
    docker:
      - image: circledan/rubybundler:latest
    executor: ruby/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          api-key: MY_HEROKU_API 
      - run:
          name: migrate db
          command: heroku run rake db:migrate --app circleciruby

  api-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: rm package-lock
          command: rm -rf package-lock.json
      - checkout 
      - run: ./app-test.sh

workflows:
  ruby-app:
    when:
      not: << pipeline.parameters.run_by_api >>
    jobs:
      - docker/publish:
          docker-username: DOCKER_LOGIN 
          docker-password: DOCKER_PASSWORD
          cache_from: '$DOCKER_USERNAME/$DOCKER_REPONAME:latest'
          image: circledan/rubybundler
          tag: latest
      - build:
          requires:
            - docker/publish
      - unit-test:
          requires:
            - build
      - lint:
          requires:
            - build
      - browser-test:
          requires:
            - build
      - deploy:
          context:
            - dan
          requires:
            - unit-test
            - lint
            - browser-test
          filters:
            branches:
              only: master

  api-workflow:
    when: << pipeline.parameters.run_by_api >>
    jobs:
      - api-job