version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: ruby:3.0.2-buster
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install bundle
          command: gem install bundler:2.2.22
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

  deploy:
    docker:
      - image: ruby:3.0.2-buster
    executor: ruby/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
        post-steps:
          - run: heroku run rake db:migrate

workflows:
  ruby-app:
    jobs:
      - build
      - deploy:
          requires:
            - build