version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.0.1

jobs:
  build:
    docker:
      - image: circledan/rubybundler:2.0
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Gem Cache
          keys: 
            - m1-{{ checksum "Gemfile.lock" }}
            - m1- 
      #- run:
          #name: install bundle
          #command: gem install bundler:2.2.22
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - save_cache:
          name: Save Gemfile Cache
          key: m1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.cache/gem

  unit-test:
    docker:
      - image: cimg/ruby:3.0.2
      - image: cimg/postgres:14.1

    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Gem Cache
          keys: 
            - m1-{{ checksum "Gemfile.lock" }}
            - m1- 
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set up DB
          command: rails db:create
      - run:
          name: Install yarn and node
          command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -; sudo apt install nodejs -y; sudo npm install --global yarn -y
      - run:
          name: Run webpack install
          command: rm bin/webpack*; rm config/webpacker.yml; rails webpacker:install
      - run:
          command: >
            mkdir -p unit-test

            bundle exec rspec spec/views --profile 10 --format RspecJunitFormatter 
            --out unit-test/results.xml --format progress
          name: Rspec views
      - store_test_results:
          path: unit-test/
      - store_artifacts:
          destination: unit-results
          path: unit-test/
      - run:
          name: run rubocop
          command: rubocop . --out check-results.xml || true
      - store_artifacts:
          path: coverage/
      - store_artifacts:
          path: check-results.xml
      - save_cache:
          name: Save Gemfile Cache
          key: m1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.cache/gem

  lint:
    docker:
      - image: cimg/ruby:3.0.2

    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Install yarn and node
          command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -; sudo apt install nodejs -y; sudo npm install --global yarn -y
      - run:
          name: run rubocop
          command: rubocop . --out check-results.xml || true
      - store_artifacts:
          path: check-results.xml

  browser-test:
    docker:
      - image: cimg/ruby:3.0.2
      - image: cimg/postgres:14.1

    executor: ruby/default
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Set up DB
          command: rails db:create
      - run:
          name: Install yarn and node
          command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -; sudo apt install nodejs -y; sudo npm install --global yarn -y
      - run:
          name: Run webpack install
          command: rm bin/webpack*; rm config/webpacker.yml; rails webpacker:install
      - run:
          command: >
            mkdir -p web-test

            bundle exec rspec spec/features --profile 10 --format RspecJunitFormatter 
            --out web-test/results.xml --format progress
          name: Rspec features
      - store_test_results:
          path: web-test/
      - store_artifacts:
          destination: web-results
          path: web-test/

  deploy:
    docker:
      - image: cimg/ruby:3.0.2
    executor: ruby/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          api-key: MY_HEROKU_API 
      - run:
          name: migrate db
          command: heroku run rake db:migrate --app circleciruby

workflows:
  ruby-app:
    jobs:
      - build
      - docker/publish:
          docker-username: DOCKER_LOGIN 
          docker-password: DOCKER_PASSWORD 
          image: circledan/rubybundler:latest
      - unit-test:
          requires:
            - build
      - lint:
          requires:
            - build
      - browser-test:
          requires:
            - build
      - deploy:
          context:
            - dan
          requires:
            - unit-test
            - lint
            - browser-test
          filters:
            branches:
              only: master