default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: myapp_dev
  host: localhost
  username: postgres

test:
  <<: *default
  database: myapp_test
  host: localhost
  username: postgres

production:
  <<: *default
  database: myapp_prod