default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  #database: db/development.sqlite3
  database: myapp_dev

test:
  <<: *default
  #database: db/test.sqlite3
  database: myapp_test

production:
  <<: *default
  #database: db/production.sqlite3
  database: myapp_prod
